Add search
RuslanYapparov/java-filmorate pull request #11
Opened 2023-05-23 18:00 UTC by Sergeyvot

В классе FilmorateConstantStorageDaoImpl оставил закоммиченные sql запросы, которыми надеялся обойтись. но почему то не сработали. Пришлось делать через сервис

2023-05-24 08:41 UTC, RuslanYapparov requested changes
Надушнил в комментариях, извини, если чем-то тебя задену, но в части исправления все получится довольно быстро (если, конечно, захочешь исправлять). Есть еще просьба по поводу нэйминга пулл-реквеста и коммитов - чтобы они не сильно выделялись из общего стиля. Например, коммиты я стараюсь оформлять как учили в теории - 
https://practicum.yandex.ru/learn/java-developer/courses/e59bc09f-08e7-4e38-ad4b-e1f3466caa68/sprints/88048/topics/e7fefc9b-02b5-488e-812e-b11212e2a348/lessons/ba96731b-7375-4258-9e57-a27091cbb096/

2023-05-24 08:41 UTC, RuslanYapparov commented on src/main/java/ru/yandex/practicum/filmorate/service/varimpl/FilmService.java
> +    List<Film> getAllBySearch(String keyWord, String parameter);
Для выполнения задания нам достаточно только сортировки по лайкам, предлагаю сделать рефакторинг и убрать метод getAllBySearch()

2023-05-24 08:41 UTC, RuslanYapparov commented on src/main/java/ru/yandex/practicum/filmorate/service/varimpl/impl/FilmServiceImpl.java
> +
Здесь также предлагаю провести мощный рефакторинг и убрать все методы, кроме вот этого, основного, переименовав его в 
```
List<Film> getMostLikedFilmsBySearch(String keyWord, String parameter);
```
А другие методы заменить стримами и рекурсией!

2023-05-24 08:41 UTC, RuslanYapparov commented on src/main/java/ru/yandex/practicum/filmorate/service/varimpl/impl/FilmServiceImpl.java
> +                return getFilmsSearchByDirector(keyWord);
Метод в классе получился очень громоздким, его можно расписать несколькими строчками стрима с вызовом уже имеющегося в классе метода: 
```
return directorService.getAll().stream()
                        .filter(director -> director.getName().toLowerCase().contains(keyWord.toLowerCase()))
                        .flatMap(director -> this.getAllFilmsByDirectorIdSortedBySomeParameter(director.getId(),
                                "likes").stream())
                        .collect(Collectors.toList());
```

2023-05-24 08:41 UTC, RuslanYapparov commented on src/main/java/ru/yandex/practicum/filmorate/service/varimpl/impl/FilmServiceImpl.java
> +
Итоговый метод получится не слишком большой, но полнофункциональный

2023-05-24 08:41 UTC, RuslanYapparov commented on src/main/java/ru/yandex/practicum/filmorate/service/varimpl/impl/FilmServiceImpl.java
> +        return filmsByDirectors;
Много логики, которая упрощается за счет использования метода .flatMap() - он может возвратить один объединенный стрим из нескольких маленьких стримов:
```
return directorService.getAll().stream()
                        .filter(director -> director.getName().toLowerCase().contains(keyWord.toLowerCase()))
                        .flatMap(director -> this.getAllFilmsByDirectorIdSortedBySomeParameter(director.getId(),
                                "likes").stream())
                        .collect(Collectors.toList());
```

2023-05-24 17:47 UTC, Sergeyvot commented on src/main/java/ru/yandex/practicum/filmorate/controller/servicecontrollers/FilmServiceController.java
> -    @Qualifier("filmService")
Также не уверен, что  "Qualifier" нужна в контроллере. Также если оставлять ее над полем, пишет warning, что lombock не берет эту аннотацию в конструктор.
Вообщем убрал совсем. работает и без нее в контроллере

2023-05-24 17:47 UTC, Sergeyvot commented on src/main/java/ru/yandex/practicum/filmorate/controller/servicecontrollers/FilmServiceController.java
> +    public List<FilmRestView> getPopularFilmsBySearch(@RequestParam(name = "query") String keyWord,
Согласен. Принято

2023-05-24 17:48 UTC, Sergeyvot commented on src/main/java/ru/yandex/practicum/filmorate/controller/servicecontrollers/FilmServiceController.java
> +                                                      @RequestParam(name = "by") String parameter) {
Замечание конструктивное. Принято

2023-05-24 17:50 UTC, Sergeyvot commented on src/main/java/ru/yandex/practicum/filmorate/controller/servicecontrollers/FilmServiceController.java
> +                + "либо имени режиссера %s", keyWord));
Принято с небольшой корректировкой

2023-05-24 17:54 UTC, Sergeyvot commented on src/main/java/ru/yandex/practicum/filmorate/dao/constimpl/FilmorateConstantStorageDaoImpl.java
Если речь про метод 
public List<E> getAll() {
        return jdbcTemplate.query(sql, objectEntityRowMapper);
    }
то этот метод из оригинального кода, не мой
Или не совсем понял данное замечание

2023-05-24 17:56 UTC, Sergeyvot commented on src/main/java/ru/yandex/practicum/filmorate/dao/constimpl/FilmorateConstantStorageDaoImpl.java
> +                sql = String.format("select f.* from %ss f "
Встречал в теории, что sql запрос с join может применяться как с AS так и без него, сразу псевдоним. То есть некритично. В любом случае метод убран)

2023-05-24 17:59 UTC, Sergeyvot commented on src/main/java/ru/yandex/practicum/filmorate/dao/constimpl/FilmorateConstantStorageDaoImpl.java
> +                        + "join directors on f.director_id = directors.director_id "
Принято. Убран.
Но почему то не срабатывал и case "title", а там нет join
Так что в чем подвох с sql запросом, осталось загадкой)

2023-05-24 17:59 UTC, Sergeyvot commented on src/main/java/ru/yandex/practicum/filmorate/service/varimpl/FilmService.java
> +    List<Film> getAllBySearch(String keyWord, String parameter);
Здесь и дальше предложения по рефакторингу - принято

2023-05-24 18:03 UTC, Sergeyvot commented on src/main/java/ru/yandex/practicum/filmorate/service/varimpl/impl/FilmServiceImpl.java
> +                           DirectorServiceImpl directorService) {
Почему сделал так. В предыдущих ТЗ (и по моему подводка шла из теории) как раз был подобный подход - объявлялась переменная типа интерфейса, а вот в конструктор уже бралась она с типом имплементирующего класса. Поэтому первоначально пошел по этому пути.
Но оставил предложенный по ревью вариант

2023-05-24 18:05 UTC, Sergeyvot commented on src/main/java/ru/yandex/practicum/filmorate/service/varimpl/impl/FilmServiceImpl.java
> +                return getFilmsSearchByDirector(keyWord);
Не очень освоил оператор flatMap. Получается как раз его мне и не хватило и пришлось лепить всю эту костыльную логику. + метод getAllFilmsByDirectorIdSortedBySomeParameter не догадался использовать

2023-05-24 19:01 UTC, RuslanYapparov commented on src/main/java/ru/yandex/practicum/filmorate/controller/servicecontrollers/FilmServiceController.java
> -    @Qualifier("filmService")
Квалифаер не нужен над контроллером, но над полями контроллера может пригодиться для подсказки спрингу, какую имплементацию брать. Ну это нужно на большущих проектах с килограммами логики, в нашем учебно-минималистичном можно не использовать...

2023-05-24 19:12 UTC, RuslanYapparov commented on src/main/java/ru/yandex/practicum/filmorate/dao/constimpl/FilmorateConstantStorageDaoImpl.java
Нет, речь была про getAllBySearch(...), просто в отображении кода все поменялось и теперь комментарий вводит в недоумение. Надо будет запомнить эту особенность, что в пулл-реквесте отображение кода может меняться. В любом случае, метод убран, все в порядке.

2023-05-24 19:15 UTC, RuslanYapparov commented on src/main/java/ru/yandex/practicum/filmorate/dao/constimpl/FilmorateConstantStorageDaoImpl.java
> +                sql = String.format("select f.* from %ss f "
Кстати, да, этот момент я запамятовал, но в теории нам описывали диалект postgreSQL, а в проекте используется h2 и у него диалект во многом отличается. Хотя по поводу АS я не знаю точно, не сталкивался, да и не важно это пока.

2023-05-24 19:34 UTC, RuslanYapparov commented on src/main/java/ru/yandex/practicum/filmorate/service/varimpl/impl/FilmServiceImpl.java
> +                return getFilmsSearchByDirector(keyWord);
Самое простое, что я уяснил для того, чтобы использовать map и flatMap - если есть поток объектов и их нужно преобразовать в другие объекты, не меняя количество, то берем map. Если количество объектов изменяется при преобразовании - то flatMap. 
По поводу использования метода getAllFilmsByDirectorIdSortedBySomeParameter теперь у меня есть сомнения... С ним происходит много обращений к базе данных, а это не очень хорошо. Но пока предлагаю оставить так, если что, оптимизировать недолго.

2023-05-24 19:37 UTC, RuslanYapparov approved these changes
Спасибо за проделанную работу и отзыв по ревью!

2023-05-25 19:02 UTC, DenchicK-64 approved these changes

2023-05-25 19:05 UTC, merged