feat: добавить фун-л поиска общих фильмов
RuslanYapparov/java-filmorate pull request #12
Opened 2023-05-26 19:30 UTC by SergeevViktor

2023-05-26 20:16 UTC, RuslanYapparov requested changes
Виктор, чувствую себя виноватым, что не подумал сразу про простой метод данной функциональности, и не сказал, чтобы ты делал так. В итоге ты сделал много сложной и долгой работы, но, я думаю, нужно переделать с простым методом, потому что ревьюер даст много замечаний. Сейчас еще подумаю над твоей второй задачей, без меня не начинай ее, пожалуйста.

2023-05-26 20:16 UTC, RuslanYapparov commented on src/main/java/ru/yandex/practicum/filmorate/dao/varimpl/impl/FilmDaoImpl.java
> +                "ORDER BY rate;";
хотел бы я знать sql так же хорошо, как ты. Мне кажется, это очень сложный запрос.

2023-05-26 20:16 UTC, RuslanYapparov commented on src/main/java/ru/yandex/practicum/filmorate/service/varimpl/impl/FilmServiceImpl.java
> +    }
Я и не думал, что логика получится такой большой! У filmService есть метод getAllFilmsLikedByUser(userId), предлагаю использовать его, тогда весь метод будет выглядеть примерно так:
```
    List<Film> filmsLikedByFirstUser = this.getAllFilmsLikedByUser(userId);
        List<Film> filmsLikedBySecondUser = this.getAllFilmsLikedByUser(anotherUserId);

        return filmsLikedByFirstUser.stream()
                .filter(filmsLikedBySecondUser::contains)
                .sorted((film1, film2) -> film2.getLikes().size() - film1.getLikes().size())
                .collect(Collectors.toList());
```
И не нужно будет использовать логику для sql-запроса и делать filmDao. Просто добавить один метод в filmService. Извини, что не настоял, когда ты спрашивал в телеграмме, чтобы ты сделал так, как я предлагал, столько времени ушло, наверное.

2023-05-27 09:21 UTC, DenchicK-64 approved these changes

2023-05-28 06:06 UTC, RuslanYapparov approved these changes

2023-05-28 11:56 UTC, merged