#1 Sprint 12
RuslanYapparov/java-filmorate pull request #2
Opened 2023-03-24 06:53 UTC by RuslanYapparov

Выполнено техническое задание проектной работы, добавлен дополнительный функционал, написаны юнит-тесты и end-to-end тест для всего приложения

2023-03-24 12:37 UTC, sergeymamonov requested changes

2023-03-24 12:37 UTC, sergeymamonov commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +	private static final User[] USERS_WITH_INVALID_DATA = {
Не очень понял, зачем нам массив невалидных данных. В тесте чем проще, тем лучше.

2023-03-24 12:37 UTC, sergeymamonov commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +	@Order(1)
Зачем эта аннотация? Тесты должны быть независимыми друг от друга и никакой порядок им не нужен.

2023-03-24 12:37 UTC, sergeymamonov commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +		assertEquals(500, response.statusCode());
Не нужно делать так, чтобы ваше приложение возвращало 500 ответ. Это значит что что-то где-то не доработано.

2023-03-24 12:37 UTC, sergeymamonov commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +		request = HttpRequest.newBuilder()
Не нужно делать много запросов в тесте. Тест должен проверять одну логику. Следующий вариант тестирования - это уже следующий тест.

2023-03-24 12:37 UTC, sergeymamonov commented on src/test/java/ru/yandex/practicum/filmorate/FilmTest.java
> +        Film film1 = Film.builder()
Я бы сделал корректный фильм один раз в BeforeEach, а в тесте бы через сеттер менял нужное значение на невалидное и тестировал.

2023-03-26 08:32 UTC, RuslanYapparov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            return ResponseEntity.notFound().build();
Создал класс FilmorateExceptionAdvice (по мануалу с хабра) для отлова введённых мною исключений и отправки клиенту сообщения из исключения с кодом статуса. Пока не придумал, как можно вернуть тело запроса в случае исключения - без возвращения тела запроса валятся предусмотренные заданием тесты на обновление объекта с неправильным id в Postman.

2023-03-26 10:51 UTC, RuslanYapparov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @GetMapping("{filmId}")
Изменил название элементов пути в методах getById и DeleteById. Добавил валидацию аннотацией @Positive

2023-03-26 10:53 UTC, RuslanYapparov commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private UserController() {           // Два экземпляра дженерик-класса, а не один (в случае аннотации над полем).
Добавил два класса, наследующихся от InMemoryStorageImpl и аннотацию @AllArgsConstructor

2023-03-26 10:57 UTC, RuslanYapparov commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        * узнать, когда и из-за чего произошла ошибка. В настройках программы установил уровень логирования DEBUG */
Пока не до конца представляю, кто такие сопровождение, но примерно так это себе и представлял. Спасибо!

2023-03-26 11:04 UTC, RuslanYapparov commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +		assertEquals(500, response.statusCode());
Для случаев указания неправильного идентификатора предусмотрел возврат статус-кода 404.

2023-03-26 11:09 UTC, RuslanYapparov commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        try {            // Аналогично с методом getById не стал обрабатывать каждую функцию с исключением отдельно
В методе были вызовы двух других методов, которые могли выбросить исключение, я обрабатывал их не отдельно, а в одном блоке catch. После внедрения FilmorateExceptionAdvice с обработкой исключений при работе контроллера блоки try-catch не используются.

2023-03-26 11:11 UTC, RuslanYapparov commented on src/main/java/ru/yandex/practicum/filmorate/customvalidation/customvalidators/BirthdayValidator.java
> +    private static final LocalDate BOUNDARY_DATE_FOR_AGE = LocalDate.of(1900, 1, 1);
Аннотация и обработчик для нее удалены

2023-03-26 11:15 UTC, RuslanYapparov commented on src/main/java/ru/yandex/practicum/filmorate/customvalidation/customvalidators/ReleaseDateValidator.java
> +    private static final LocalDate CINEMA_BIRTHDAY = LocalDate.of(1895, 12, 28);
Константа переименована в EARLIEST_RELEASE_DATE

2023-03-26 11:24 UTC, RuslanYapparov commented on src/main/java/ru/yandex/practicum/filmorate/customvalidation/customvalidators/UserValidator.java
> +public class UserValidator {
К сожалению, не понял, что имеется ввиду. В классе было 2 метода, которые проверяли поля объекта User на условия, валидацию которых не смог организовать с помощью аннотаций. В нем не делалось дополнительных действий. На всякий случай переименовал в UserEmailAndNameValidator

2023-03-26 11:28 UTC, RuslanYapparov commented on src/main/java/ru/yandex/practicum/filmorate/customvalidation/customvalidators/UserValidator.java
> +    public static void checkUsersEmailForDuplication(User user, List<User> savedUsers) throws ValidationException {
Также не понял, что имеется ввиду. Метод проверяет не был ли сохранен пользователь с таким же адресом email. Дополнительные действия не выполняются.

2023-03-26 11:37 UTC, RuslanYapparov commented on src/main/java/ru/yandex/practicum/filmorate/customvalidation/customvalidators/UserValidator.java
> +    public static User checkUserNameAndReturnValidUser(User user) {
Переименовал метод в User getUserWithCheckedName(User)

2023-03-26 17:00 UTC, RuslanYapparov commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        /* Валидация пользователей реализована с помощью аннотаций (в том числе, собственных), но для полей email
Из того, что не проверяет аннотация @Email путем экспериментов нашел проверку на наличие точки во второй части адреса. Добавил эту проверку в UserEmailAndNameValidator

2023-03-26 17:07 UTC, RuslanYapparov commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +	private static final User[] USERS_WITH_INVALID_DATA = {
Для каждого элемента массивов введен отдельный тест-метод. Массивы удалены.

2023-03-26 17:13 UTC, RuslanYapparov commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +	@Order(1)
Упорядоченный вызов тест-методов, как я думал, сокращал количество кода и упрощал логику end-to-end тестирования (учитывая, что методы всех составляющих классов уже были проверены в юнит-тестах в формате независимого вызова). После замечания все аннотации убраны, тесты проводятся без определенного сценария.

2023-03-26 17:16 UTC, RuslanYapparov commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +		request = HttpRequest.newBuilder()
В методе с аннотацией @BeforeEach получилось 4 запроса (по 2 к разным контроллерам), в остальных тест-методах постарался максимально сократить количество запросов (1-2 запроса)

2023-03-26 17:19 UTC, RuslanYapparov commented on src/test/java/ru/yandex/practicum/filmorate/FilmTest.java
> +        Film film1 = Film.builder()
Сделано в соответствии с советом (только изменение не через сеттер, а через создание нового объекта через Builder (думал, что лучше делать неизменяемые объекты)

2023-03-26 17:20 UTC, closed without merging