Sprint 12 (Group project) all features for code-review
RuslanYapparov/java-filmorate pull request #20
Opened 2023-05-29 17:55 UTC by RuslanYapparov

Здравствуйте! Где-то читал, что ревьюеру необходимо предоставить краткую сводку по групповой работе:
Реализовали с командой все функциональности, указанные в задании для проверки ревьюером. Требовал от членов команды сохранения общего стиля (использование стримов и функционального стиля, наследования и имплементации интерфейсов, зачатков применения CQRS-паттерна и слоенной архитектуры, мэпперов библиотеки mapstruct), для понимания один раз собирались в зуме, где я пытался все объяснить. Не для всех структура и логика работы моего проекта оказалась легкой, пару раз из-за установленных эстимейтов приходилось исправлять и допиливать самому. Также при исправлении конфликтов один раз зашли в тупик (как показалось на тот момент) и использовал форс-пуш, поэтому коммитов одного из членов команды нет - все они, соответственно перезаписаны на мои (зато узнал, как это работает).

2023-05-30 16:14 UTC, sergeymamonov requested changes
Пример, FriendshipEntity и FilmEntity и др. классы иммутабельность достигается по-разному. Лучше сделать одним способом.

Попробуйте убрать @Qualifier там, где без него можно обойтись.

2023-05-31 14:02 UTC, RuslanYapparov commented on src/main/java/ru/yandex/practicum/filmorate/controller/servicecontrollers/FilmServiceController.java
>  package ru.yandex.practicum.filmorate.controller.servicecontrollers;
Произвел рефакторинг - все имена пакетов, слитые из двух слов, переведены в snake_case

2023-05-31 14:03 UTC, RuslanYapparov commented on src/main/java/ru/yandex/practicum/filmorate/controller/servicecontrollers/FilmServiceController.java
> +            @RequestParam(name = "genreId") Optional<Integer> genreId,
Произведены рефакторинг и оптимизация метода для использования с примитивным типом int и значениями по умолчанию

2023-05-31 14:05 UTC, RuslanYapparov commented on src/main/java/ru/yandex/practicum/filmorate/controller/servicecontrollers/RecommendationServiceController.java
> +    @Qualifier("filmService")
Все аннотации "qualifier" во всех классах удалены, необходимости в их использовании не было, но было предложено использовать в техническом задании проектной работы предыдущего спринта

2023-05-31 14:09 UTC, RuslanYapparov commented on src/main/java/ru/yandex/practicum/filmorate/dao/varimpl/impl/UserDaoImpl.java
>          return this.getById(keyHolder.getKey().longValue());
Проверка на null в данном выражении произведена с помощью методов ofNullable(...) и orElseThrow(...) класса Optional. Продублировано во всех имплементациях dao-интерфейсов, где использовалось сохранение с получением идентификатора.

2023-05-31 14:11 UTC, RuslanYapparov commented on src/main/java/ru/yandex/practicum/filmorate/mapper/EventMapper.java
> +    @Mapping(target = "timestamp", source = "timestamp", qualifiedByName = "mapTimestamp")
Воспользовался данной возможностью в EventMapper, UserMapper и FilmMapper для полей, мэппинг которых умещается в одну строку.

2023-05-31 14:12 UTC, RuslanYapparov commented on src/main/java/ru/yandex/practicum/filmorate/service/varimpl/FilmService.java
> +    List<Film> getMostLikedFilmsWithFilters(int count, Optional<Integer> genreId, Optional<Integer> year);
Метод изменен для использования int-параметров

2023-05-31 21:14 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controller/servicecontrollers/RecommendationServiceController.java
> +    @Qualifier("filmService")
Если бы мы создавали несколько различных бинов одного класса, тогда да, нужно было бы пользоваться аннотацией @Qualifier. Но если создается один бин, то тогда не нужно добавлять @Qualifier, чтобы не загромождать код.

2023-05-31 21:23 UTC, sergeymamonov approved these changes

2023-05-31 21:23 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/mapper/EventMapper.java
> +                throw new RuntimeException("Внутренняя ошибка приложения, связанная с определением типа объекта, " +
Лучше не RuntimeException кидать, а кидать свою ошибку. Потому что при разборе логов сложнее понять, где выскочила RuntimeException, а где она была ожидаема. Поэтому везде, где в коде кидается RuntimeException лучше переделать на свою или уже существующую специфическую ошибку.

2023-05-31 21:23 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/mapper/EventMapper.java
> +    @Mapping(target = "eventType", source = "eventType", qualifiedByName = "mapEventTypeFromString")
Думаю, эти две строки явного указания маппинга не нужны. Попробуйте без них, мапстрак сам подтянет методы конвертации.

2023-06-01 07:17 UTC, RuslanYapparov commented on src/main/java/ru/yandex/practicum/filmorate/mapper/EventMapper.java
> +                throw new RuntimeException("Внутренняя ошибка приложения, связанная с определением типа объекта, " +
Интерфейс оптимизирован, данные мэппинг-методы удалены, В 5-и местах выбрасывание RuntimeException заменено на свое исключение InternalLogicException

2023-06-01 07:18 UTC, RuslanYapparov commented on src/main/java/ru/yandex/practicum/filmorate/mapper/EventMapper.java
> +    @Mapping(target = "eventType", source = "eventType", qualifiedByName = "mapEventTypeFromString")
Действительно, все заработало без них, mapstruct справился сам.

2023-06-01 07:27 UTC, merged