#2 Sprint 9
RuslanYapparov/java-filmorate pull request #3
Opened 2023-03-26 17:33 UTC by RuslanYapparov

Спасибо за советы и замечания! Постарался все исправить, но в 2-х случаях не разобрался, что имелось ввиду. Под каждым комментарием предыдущей проверки кратко расписал, что сделано (а в некоторых еще - почему изначально сделал так, как сделал до исправления).

2023-03-27 04:16 UTC, sergeymamonov requested changes
В тестах рекомендовал бы выделять какие-то блоки в отдельные методы. Потом можно увидеть, что часть методов будет похожа друг на друга и можно будет объединить два метода в один, но с параметрами. Плюс тесты будет короче, но читаемее.

2023-03-27 04:16 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getId() == 9999) {   // Костыль для прохождения теста в Postman (требуется при проверке в GitHub)
Я первый раз такое вижу и не слышал ранее о такой проверке. Точна она нужна и причем именно с этим числом?

2023-03-27 04:16 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        * и name есть особые условия проверки, для которых не придуммал способ реализации через аннотации.
Есть аннотация для проверки почты @Email.

2023-03-27 04:16 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/handler/FilmorateExceptionAdvice.java
> +public class FilmorateExceptionAdvice {
Обычно называют ...ExceptionHandler

2023-03-27 04:16 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/handler/FilmorateExceptionAdvice.java
> +
Сюда можно добавить внутреннюю ошибку приложения - статус ответа 500.

2023-03-27 04:16 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Film(@JsonProperty("id") int id, @JsonProperty("name") String name,
Обычно делают класс команды (command) в котором прописывают аннотации @JsonProperty над полями. А в этом классе не обязательно будет писать конструктор руками, а можно будет использовать аннотацию @AllArgsConstructor. 

Создание класса команды по желанию, не настаиваю на этом изменении.

2023-03-27 05:04 UTC, RuslanYapparov commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +	// Также пытался завершить работу приложения в методе с аннтоцией @AfterAll, но пришлось отказаться из-за ошибок,
Получается, в случае тест-класса это пригодилось бы только для тестирования того, что приложение способно завершиться. Думаю, для Spring-приложения это необязательно, учитывая, сколько высоких умов развивают эти технологии.

2023-03-27 05:04 UTC, RuslanYapparov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getId() == 9999) {   // Костыль для прохождения теста в Postman (требуется при проверке в GitHub)
Переписал комментарий с отражением теста Postman

2023-03-27 05:35 UTC, RuslanYapparov commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        * и name есть особые условия проверки, для которых не придуммал способ реализации через аннотации.
Получается, я дважды ввел в заблуждение со своим комментарием - аннотация @Email была использована с самого начала, но она не проверяет, что ранее был сохранен пользователь с таким же адресом электронной почты. Этот момент проверяю в отдельном методе класса UserEmailAndNameValidator, а еще нашел один момент, который не проверяет аннотация (наличие точки во второй части адреса), поэтому добавил соответствующую проверку.

2023-03-27 05:42 UTC, RuslanYapparov commented on src/main/java/ru/yandex/practicum/filmorate/handler/FilmorateExceptionAdvice.java
> +public class FilmorateExceptionAdvice {
Переименовал в IntroducedExceptionsHandler

2023-03-27 05:45 UTC, RuslanYapparov commented on src/main/java/ru/yandex/practicum/filmorate/handler/FilmorateExceptionAdvice.java
> +
Заменил статус BAD_REQUEST на INTERNAL_SERVER_ERROR

2023-03-27 10:18 UTC, RuslanYapparov commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +		film = film.toBuilder().description("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" +
Применил данный метод String

2023-03-28 13:16 UTC, RuslanYapparov commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Film(@JsonProperty("id") int id, @JsonProperty("name") String name,
Потратил много времени и сил на поиски вариантов и попытки реализации классов-команд, спрашивал совета у наставника и, получилось, через него у код-ревьюера, но что-то пока ускользает из моего понимания. И данные классы пока не ввёл, но займусь ими в следующей проектной работе (как раз ожидается что-то похожее в теории курса)

2023-03-28 13:19 UTC, closed without merging