#5 Sprint 10
RuslanYapparov/java-filmorate pull request #5
Opened 2023-04-09 08:23 UTC by RuslanYapparov

2023-04-10 19:44 UTC, sergeymamonov requested changes
Если хотите еще с чем-то промышленным из архитектуры познакомиться, то можете посмотреть https://medium.com/design-microservices-architecture-with-patterns/cqrs-design-pattern-in-microservices-architectures-5d41e359768c

Реализовывать или нет в проекте по желанию. Изменение будет достаточно большое по работе и не факт, что после этого будут проходить автотесты, так как это на курсе не проходится

2023-04-10 19:44 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controller/servicecontrollers/FilmServiceControllerImpl.java
> +    public List<FilmRestCommand> getPopularFilms(@RequestParam(name = "count", defaultValue = "10")
Если делать более приближенным на промышленный вариант, то возвращать мы должны не FilmRestCommand, а FilmRestView - это класс представление. Не всегда, он совпадает с классом ...command. Исправление на ваше усмотрение, я не настаиваю.

2023-04-10 19:44 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmorateExceptionsHandler.java
> +
Можно добавить еще обработку необрабатываемой ошибки и возвращать 500 статус.

2023-04-10 19:44 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/customvalidation/customvalidators/UserEmailAndNameValidator.java
> +    private static final Validator validator = Validation.buildDefaultValidatorFactory().getValidator();
Поле где-то используется?

2023-04-10 19:44 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/model/controllercommandclasses/restcommand/impl/FilmRestCommand.java
> +            this.likes.forEach(id -> film.getLikes().add(id));
Есть еще id, которое поле этого класса. Хоть у них и разные области видимости, но лучше не давать одинаковых названий переменным.

2023-04-10 19:44 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/model/controllercommandclasses/restcommand/impl/UserRestCommand.java
> +            this.friends.forEach(id -> user.getFriends().add(id));
Аналогично. Лучше дать другое название переменной.

2023-04-10 19:44 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/model/controllercommandclasses/restcommand/impl/UserRestCommand.java
> +    public User convertToDomainObject() throws UserValidationException {
Конвертации в этом классе не место. Для этого лучше создать еще один класс.

2023-04-11 10:33 UTC, RuslanYapparov commented on src/main/java/ru/yandex/practicum/filmorate/controller/servicecontrollers/FilmServiceControllerImpl.java
> +    public List<FilmRestCommand> getPopularFilms(@RequestParam(name = "count", defaultValue = "10")
Реализовал классы-представления, добавил в логику для контроллеров, сервисов и тестов. Остался вопрос по поводу использования аннотаций lombok в классах доменных моделей - допускается ли их использование по принципам гексогональной архитектуры? Ведь получается интеграция слоя фрейморка в доменный слой.

2023-04-11 11:32 UTC, RuslanYapparov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmorateExceptionsHandler.java
> +
Добавил метод  handleAnotherUnhandledException(RuntimeException exception), возвращающий ответ ошибки с 500-ым статусом. Проверил работу с помощью добавления в метод контроллера деления на ноль. Проверил работу прочих методов-обработчиков ошибок. Все работает.

2023-04-11 11:46 UTC, RuslanYapparov commented on src/main/java/ru/yandex/practicum/filmorate/customvalidation/customvalidators/UserEmailAndNameValidator.java
> +    private static final Validator validator = Validation.buildDefaultValidatorFactory().getValidator();
Поле используется при тестировании аннотаций (в том числе, 2-х самодельных).
Set<ConstraintViolation<UserRestCommand>> userViolations = validator.validate(createCommandObjectForTest(user));

Понимаю, что тестирую в этом тест-классе инструмент, который разработчики уже протестировали вдоль и поперек, но это больше из личного интереса и для понимания принципов работы. Ещё понимаю, что уместнее было бы использовать интеграционное тестирование, которое пока не изучал, оно дальше по курсу, с ним решил не торопиться.

2023-04-11 12:06 UTC, RuslanYapparov commented on src/main/java/ru/yandex/practicum/filmorate/model/controllercommandclasses/restcommand/impl/FilmRestCommand.java
> +            this.likes.forEach(id -> film.getLikes().add(id));
Пробежался по коду в пакете main, переименовал все неоднозначные и сокращенные переменные

2023-04-11 12:07 UTC, RuslanYapparov commented on src/main/java/ru/yandex/practicum/filmorate/model/controllercommandclasses/restcommand/impl/UserRestCommand.java
> +            this.friends.forEach(id -> user.getFriends().add(id));
Переименовано в friendId

2023-04-11 12:21 UTC, RuslanYapparov commented on src/main/java/ru/yandex/practicum/filmorate/model/controllercommandclasses/restcommand/impl/UserRestCommand.java
> +    public User convertToDomainObject() throws UserValidationException {
Создал утилитарные классы для конвертирования внешних представлений в доменные объекты и обратно.

2023-04-11 12:52 UTC, RuslanYapparov commented
Спасибо за интересную статью! Разделение на поступающие и выводящиеся сущности я постарался реализовать, но по поводу полноценного применения CQRS-паттерна с двумя базами данных и устройства их согласованной работы, подумаю, когда дойду до ТЗ текущего спринта и посоветуюсь с наставником.

2023-04-12 03:56 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controller/servicecontrollers/FilmServiceControllerImpl.java
> +    public List<FilmRestCommand> getPopularFilms(@RequestParam(name = "count", defaultValue = "10")
Тут вопрос уже на чем остановиться. С точки зрения чистой архитектуры Ломбок в доменном слое это нехорошо. Но тогда придется вручную писать геттеры, сеттеры и пр. Поэтому идут на компромис и ломбок в доменном слое используют. Но вот спринг в доменном слое уже не используют, без него можно обойтись.

2023-04-12 04:06 UTC, sergeymamonov approved these changes

2023-04-12 04:06 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/model/restinteractionmodel/restview/FilmRestView.java
> +    String name;
Аннотация Data содержит в себе много других аннотаций. Лучше взять из нее только то, что нужно. Полям добавить приватный модификатор. То есть сделать класс иммутабельным. Общее правило, если можно сделать класс иммутабельным, то лучше сделать. А как раз классы ...command, ...view чаще всего они иммутабельны.

2023-04-12 04:06 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/util/UserObjectConverter.java
> +    public static UserRestView toRestView(User user) {
Если будет желание, то посмотрите библиотеку MapStruct, чтобы конвертировать объекты было проще.

2023-04-12 04:06 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/util/UserObjectConverter.java
> +package ru.yandex.practicum.filmorate.util;
util - это что-то такое совсем специфическое помещают в подобные пакеты. Конвертация - это рядовое действие. То есть мы конвертируем из пришедших данных в домен, из домена в представление. Поэтому и пакет лучше назвать converter, mapper и еще как-то, но чтобы было сразу понятно, что здесь конвертеры.

2023-04-12 04:37 UTC, RuslanYapparov commented on src/main/java/ru/yandex/practicum/filmorate/model/restinteractionmodel/restview/FilmRestView.java
> +    long id;
Добавил аннотации JsonProperty над полями всех классов-представлений

2023-04-12 05:24 UTC, RuslanYapparov commented on src/main/java/ru/yandex/practicum/filmorate/model/restinteractionmodel/restview/FilmRestView.java
> +    String name;
Убрал аннотацию Data в классах-представлениях, установил приватный модификатор доступа к полям, подобрал необходимый набор  аннотаций, для ErrorResponseView пришлось написать конструктор вручную, из-за наличия поля, которое задействуется только для особенного типа исключения.

2023-04-12 11:20 UTC, RuslanYapparov commented on src/main/java/ru/yandex/practicum/filmorate/util/UserObjectConverter.java
> +    public static UserRestView toRestView(User user) {
Добавил библиотеку MapStruct, реализовал генерацию объектов-MapperImpl и их работу в условиях приложения

2023-04-12 11:22 UTC, RuslanYapparov commented on src/main/java/ru/yandex/practicum/filmorate/util/UserObjectConverter.java
> +package ru.yandex.practicum.filmorate.util;
Переименовал пакет в converter, а затем, после внедрения MapStruct удалил за ненадобностью вместе с реализациями классов-конвертеров.

2023-04-12 11:40 UTC, merged