Sprint 11
RuslanYapparov/java-filmorate pull request #7
Opened 2023-05-03 19:48 UTC by RuslanYapparov

В очередной раз благодарю за интересные советы и комментарии прошлой проверки. 
CQRS паттерн, про который Вы мне советовали почитать, показался весьма интересным, попробую использовать его в своем пет-проекте. Но в данном учебном проекте с использованием 2х баз данных на чтение и запись довольно много ограничений и проверок (наставник посоветовал пока не заморачиваться, а оставить для собственного ознакомления). 
В данном проекте пока не реализовал интеграционное тестирование, даже представленное в техническом задании (в нем, как я понял, используется junit4, который не включен в используемой версии spring-boot-starter-test, а добавлять его ради нескольких тестов я не стал). Оставлю интеграционное тестирование для будущих проектных работ, если Вы не возражаете.

2023-05-04 18:57 UTC, sergeymamonov commented
> В очередной раз благодарю за интересные советы и комментарии прошлой проверки. CQRS паттерн, про который Вы мне советовали почитать, показался весьма интересным, попробую использовать его в своем пет-проекте. Но в данном учебном проекте с использованием 2х баз данных на чтение и запись довольно много ограничений и проверок (наставник посоветовал пока не заморачиваться, а оставить для собственного ознакомления). В данном проекте пока не реализовал интеграционное тестирование, даже представленное в техническом задании (в нем, как я понял, используется junit4, который не включен в используемой версии spring-boot-starter-test, а добавлять его ради нескольких тестов я не стал). Оставлю интеграционное тестирование для будущих проектных работ, если Вы не возражаете.

CQRS паттерн могут применять и с одной БД (то есть и брокер сообщений не нужен). А паттерн используется только в разделении модулей модуль command и модуль query. И в каждом это модуле уже реализована архитектура приложения, в одном на изменение данных, а во втором на запрос данных.

Согласен с наставником, что знакомство с паттерном хорошо, но это значительно усложнит код учебного проекта.

2023-05-04 20:36 UTC, sergeymamonov requested changes

2023-05-04 20:36 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/mapper/FilmMapper.java
> +    default Set<Long> mapLikesSet(Set<Long> likesSet) {
Mapstruct мощный инструмент и часть из того, что здесь написано, он может сделать сам. Например, маппинг коллекций. В этом методе нет необходимости можно просто указать какое поле в какое мапить.

2023-05-04 20:36 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/model/data/FilmEntity.java
> +@lombok.Value     // Мне кажется, экземпляры дата-классов по логике должны быть immutable-объектами, поэтому использую
Да, использование иммутабельных классов - это очень круто. Здесь применить не получится, так как версия Java 11, но в более поздних версиях можно использовать record.

2023-05-04 20:36 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/model/presentation/restview/FilmRestView.java
Создавать объект через билдер вполне нормально.

2023-05-04 20:36 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/service/varimpl/impl/FilmServiceImpl.java
> +        List<Genre> oldGenresList = this.filmGenreDao.getAllGenresOfFilmByFilmId(filmId);
Здесь не обязательно писать this.

2023-05-05 05:15 UTC, RuslanYapparov commented on src/main/resources/schema.sql
> +  email varchar NOT NULL UNIQUE,
Для всех колонок с типом varchar добавил ограничение на длину строки.

2023-05-05 05:26 UTC, RuslanYapparov commented on src/main/java/ru/yandex/practicum/filmorate/controller/servicecontrollers/FilmServiceControllerImpl.java
> +public class FilmServiceControllerImpl {
Интерфейсы сервисных контроллеров убрал (после того, как спросил мнения наставника о их необходимости), а названия классов изменить забыл. 
Исправился.

2023-05-05 06:07 UTC, RuslanYapparov commented on src/main/java/ru/yandex/practicum/filmorate/controller/servicecontrollers/FilmServiceControllerImpl.java
> +            throws ObjectNotFoundInStorageException {
Так исключение, наверное, передавалось в метод main спринг-приложения, а обработчик ошибок задействован в слое контроллера, и получается несоответствие, да? 
Удалил проброс исключения в вышестоящий метод во всех методах контроллеров.

2023-05-05 06:11 UTC, RuslanYapparov commented on src/main/java/ru/yandex/practicum/filmorate/controller/storagecontrollers/constimpl/GenreStorageControllerImpl.java
> +@lombok.extern.slf4j.Slf4j
Когда увидел такой способ аннотирования в теории, то зачем-то решил для себя, что он более мне подходит - не сильно, но разгружает количество строк импортов и, таким образом, снижает общее количество строк кода. 
Вероятно, это не очень хорошо, переделал все аннотации в обычный вид.

2023-05-05 08:59 UTC, RuslanYapparov commented on src/main/java/ru/yandex/practicum/filmorate/mapper/FilmMapper.java
> +    default Set<Long> mapLikesSet(Set<Long> likesSet) {
Не смог найти способ, чтобы в имплементации производилось действие при значении поля likes = null. Применение парамтеров nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.SET_TO_DEFAULT, nullValueCheckStrategy = NullValueCheckStrategy.ALWAYS не помогло, в FilmMapperImpl все равно обработка поля выглядела так:

     Set<Long> set1 = filmRestCommand.getLikes();
        if ( set1 != null ) {
            film.likes( new LinkedHashSet<Long>( set1 ) );
        }

В результате получал NPE. Пока решил оставить такое дефолтное определение метода */

2023-05-05 09:10 UTC, RuslanYapparov commented on src/main/java/ru/yandex/practicum/filmorate/model/data/FilmEntity.java
> +@lombok.Value     // Мне кажется, экземпляры дата-классов по логике должны быть immutable-объектами, поэтому использую
Почитал про Record, показалось интересным, что такую функциональность решили реализовать на уровне языковых средств, в то время как есть фрэймворки типа Lombok или, например, средства Idea, позволяющие реализовать те же функции. В любом случае, это было бы полезно, жалко, что доступно только с 16й джавы.

2023-05-05 09:11 UTC, RuslanYapparov commented on src/main/java/ru/yandex/practicum/filmorate/model/presentation/restview/FilmRestView.java
Убрал использование сеттера в одном методе (заменил на builder), убрал данную аннотацию и добавил параметр toBuilder в соответствующей аннотации класса.

2023-05-05 09:22 UTC, RuslanYapparov commented on src/main/java/ru/yandex/practicum/filmorate/service/varimpl/impl/FilmServiceImpl.java
> +        List<Genre> oldGenresList = this.filmGenreDao.getAllGenresOfFilmByFilmId(filmId);
Пробежался по коду - убрал все ссылки на поля объектов с помощью this. Но оставил ссылки на методы объекта.

2023-05-05 09:31 UTC, RuslanYapparov commented
Спасибо за полезные советы и информацию!
Не смог реализовать совет по использованию функционала mapstruct, получал NPE несмотря на предпринятые меры (в комментариях к PR и в самих интерфейсах-mapper расписал). В остальном, постарался исправить все в соответствии с Вашими комментариями.

2023-05-06 10:35 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/mapper/FilmMapper.java
> +    default Set<Long> mapLikesSet(Set<Long> likesSet) {
Я писал, что можно не подсказывать как из одной коллекции в другую mapstruk конвертировать. Он и сам это сделает. Главное указать какой объект в какой конвертировать. Если будет что-то непонятно, пишите в Пачке.

2023-05-06 10:36 UTC, sergeymamonov approved these changes

2023-05-10 07:32 UTC, merged